name: fashion_mnist_demo
seed: 42
device: auto              # "auto", "cpu", "cuda", or "mps"
mixed_precision: true     # use torch.cuda.amp if available
deterministic: true

paths:
  runs_root: ./runs

loggers:
  csv: true
  jsonl: true
  tensorboard: true
  wandb: false
  project: exp-tracker-demo  # wandb project name if enabled

trainer:
  max_epochs: 3
  log_every_steps: 100
  val_every_epochs: 1
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 3
    min_delta: 1e-4
  grad_clip_norm: 1.0

optim:
  lr: 0.001
  weight_decay: 0.0
  betas: [0.9, 0.999]

data:
  batch_size: 64
  num_workers: 2

model:
  hidden_dim: 256

resume: null     # path to a previous run dir to resume from; or null
